# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Steven Haussmann
title: Computer Science Graduate Student
email: hausss@rpi.edu
website: www.github.com/Etherealflux

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  etherealflux
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a graduate student in the field of computer science. My research is directed towards program obfuscation and the study thereof. I greatly enjoy teaching, and have found working as a teaching assistant to be very fulfilling.

  I am the current president of RPISEC, which is RPI's security club.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rose-Hulman Institute of Technology
        caption: 2013 - 2017
        sub_title: BSc Computer Science & BSc Chemistry
        description: | # this will include new lines to allow paragraphs
          Being uncertain about where my interests would settle &mdash; chemistry or computer science &mdash; I wound up pursuing both. This required a great deal of time and dedication, but gave me a very broad body of knowledge.
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: 2017 - *
        sub_title: Pursuing a PhD in Computer Science
        description: | # this will include new lines to allow paragraphs
          I am currently a doctoral student at RPI, as described above.
          
  - title: Teaching Assistant Experience
    layout: list
    content:
      - layout: left
        title: CSCI-1200 Data Structures
        caption: Spring 2022
        description: I consider this to be a "formative" class for CS majors &mdash; it is where they are first exposed to a vast range of vital topics. So, it is essential that students receive all the guidance they need to come out with a good understanding of the material.
      - layout: left
        title: CSCI-2300 Introduction to Algorithms 
        caption: Fall 2021
      - layout: left
        title: CSCI-4230 Cryptography and Network Security I
        caption: Fall 2021
        description: I have TA'd this course twice now (and am hoping to do so for a third time this summer). Going through the material several times has greatly strengthed my understanding of cryptography, and I'm looking forward to continue sharing that knowledge.
      - layout: left
        title: CSCI-4380 Database Systems
        caption: Spring 2021
      - layout: left
        title: CSCI-4230 Cryptography and Network Security I
        caption: Spring 2021
      - layout: left
        title: CSCI-4430 Programming Languages
        caption: Fall 2020
        description: Programming Languages is a major opportunity to expose students to new ideas. My only regret is that it's not taught sooner.
      - layout: left
        title: CSCI-4450 Program Analysis
        caption: Spring 2020
      - layout: left
        title: CSCI-4430 Programming Languages
        caption: Fall 2019
      - layout: left
        title: PHYS-1200 Physics II
        caption: Fall 2017
        description: Since I have a background in chemistry, I was assigned to a physics class during my first semester at RPI.

  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Internship at Indigo BioAutomation
        caption: Summer 2015
        description: I interned at [Indigo BioAutomation](https://www.indigobio.com) during my time at Rose-Hulman. I mostly focused on web development, learning to use Ruby/Ruby on Rails to add features to their product.
      - layout: left
        title: Instruction at iD Tech Summer Camps
        caption: Summer 2016
        description: I taught a variety of topics to children ranging from early middle school to late high school, including programming in Java and developing game mods.

  - title: Programming Experience
    layout: list
    content:
    - layout: left
      title: Languages
      description: |
        I have experience in the following programming languages, ranked roughly from most to least familiarity:
        - Python
        - C++
        - Java
        - C
        - Haskell
    - layout: left
      title: Topics
      description: |
        Some general topics that I have significant experience with are, in no particular order:
        - Reverse engineering
        - Large-scale data collection and analysis
        - Cryptography
        - Client and server-side web exploitation
  - title: Other Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have a very broad range of miscellaneous experience:
      - Physical security and lockpicking
      - Competitive cybersecurity events (aka Capture The Flag/CTF games)

      I enjoy poking holes in things and seeing how they break.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
